---
# tasks file for supabase
- name: Install Git, Podman and Epel
  become: true
  package:
    name:
      - epel-release
      - git
      - podman
    state: present

- name: Install podman compose
  become: true
  ansible.builtin.package:
    name:
      - podman-compose
    state: present

- name: Clone Supabase repository
  become: true
  ansible.builtin.git:
    repo: https://github.com/supabase/supabase
    dest: "{{ supabase_path }}"
    depth: 1

- name: Generate Supabase .env file
  become: true
  ansible.builtin.template:
    src: "templates/supabase_env.j2"
    dest: "{{ supabase_path }}/docker/.env"
    owner: "{{ server_user }}"
    group: "{{ server_group }}"
    mode: "0600"

- name: Start Supabase instance using podman-compose
  #become: true
  shell: "podman-compose -f {{ supabase_path }}/docker/docker-compose.yml up -d"
  args:
    executable: /bin/bash
